// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACWUT8_n_UCF4UkIQDTe3Xomx0aNVFwfI',
    appId: '1:665831928342:web:c39f5b529affa05e353b37',
    messagingSenderId: '665831928342',
    projectId: 'fir-project-95c29',
    authDomain: 'fir-project-95c29.firebaseapp.com',
    storageBucket: 'fir-project-95c29.firebasestorage.app',
    measurementId: 'G-KVVRB9XCQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4V0CHHizDkpuROrgtfRSHFng41nG5xBg',
    appId: '1:665831928342:android:5072ac1489cfc1ef353b37',
    messagingSenderId: '665831928342',
    projectId: 'fir-project-95c29',
    storageBucket: 'fir-project-95c29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnI76QkSWFhwxxx0szep9xXuA0PQhUSw',
    appId: '1:665831928342:ios:ce6f2b25595495d4353b37',
    messagingSenderId: '665831928342',
    projectId: 'fir-project-95c29',
    storageBucket: 'fir-project-95c29.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnI76QkSWFhwxxx0szep9xXuA0PQhUSw',
    appId: '1:665831928342:ios:ce6f2b25595495d4353b37',
    messagingSenderId: '665831928342',
    projectId: 'fir-project-95c29',
    storageBucket: 'fir-project-95c29.firebasestorage.app',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACWUT8_n_UCF4UkIQDTe3Xomx0aNVFwfI',
    appId: '1:665831928342:web:f0c8e064e78a543c353b37',
    messagingSenderId: '665831928342',
    projectId: 'fir-project-95c29',
    authDomain: 'fir-project-95c29.firebaseapp.com',
    storageBucket: 'fir-project-95c29.firebasestorage.app',
    measurementId: 'G-LLT8N3G6WV',
  );
}
